---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Hussam's Homelab
theme: dark
color: slate
background:
  image: https://picsum.photos/seed/homelab/16/9
  blur: xs
  brightness: 50
  saturate: 100
cardBlur: xs
