---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- greeting:
    text_size: 3xl
    text: Welcome back, Hussam

- datetime:
    text_size: xl
    format:
      dateStyle: full
      timeStyle: short
      hour12: true

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    units: metric

- glances:
    url: http://127.0.0.1:61208
    version: 4
    cpu: false
    mem: false
    cputemp: true
    cpuSensorLabel: Composite
    label: SSD

- search:
    provider: duckduckgo
    target: _blank
